

function StartVehMods ()
    nav = engineLoadTXD("nav.txd", 599)  
    engineImportTXD(nav, 599)
	nav = engineLoadDFF("nav.dff", 599) 
	engineReplaceModel(nav, 599)
    csomag = engineLoadTXD("csomag.txd", 414)  
    engineImportTXD(csomag, 414)
	csomag = engineLoadDFF("csomag.dff", 414) 
	engineReplaceModel(csomag, 414)
    taxi = engineLoadTXD("taxi.txd", 420)  
    engineImportTXD(taxi, 420)
	taxi = engineLoadDFF("taxi.dff", 420) 
	engineReplaceModel(taxi, 420)
    bus = engineLoadTXD("bus.txd", 431)  
    engineImportTXD(bus, 431)
	bus = engineLoadDFF("bus.dff", 431) 
	engineReplaceModel(bus, 431)
   heli = engineLoadTXD("heli.txd", 497)  
    engineImportTXD(heli, 497)
	heli = engineLoadDFF("heli.dff", 497) 
	engineReplaceModel(heli, 497)
   bmwter = engineLoadTXD("bmwter.txd", 579)  
    engineImportTXD(bmwter, 579)
	bmwter = engineLoadDFF("bmwter.dff", 579) 
	engineReplaceModel(bmwter, 579)
	tur = engineLoadTXD("tur.txd", 451)  
    engineImportTXD(tur, 451)
	tur = engineLoadDFF("tur.dff", 451) 
	engineReplaceModel(tur, 451)
	wind = engineLoadTXD("wind.txd", 401)  
    engineImportTXD(wind, 401)
	wind = engineLoadDFF("wind.dff", 401) 
	engineReplaceModel(wind, 401)
	land = engineLoadTXD("land.txd", 400)  
    engineImportTXD(land, 400)
	land = engineLoadDFF("land.dff", 400) 
	engineReplaceModel(land, 400)
	lam = engineLoadTXD("lam.txd", 402)  
    engineImportTXD(lam, 402)
	lam = engineLoadDFF("lam.dff", 402) 
	engineReplaceModel(lam, 402)
	audi = engineLoadTXD("audi.txd", 405)  
    engineImportTXD(audi, 405)
	audi = engineLoadDFF("audi.dff", 405) 
	engineReplaceModel(audi, 405)
	per = engineLoadTXD("per.txd", 404)  
    engineImportTXD(per, 404)
	per = engineLoadDFF("per.dff", 404) 
	engineReplaceModel(per, 404)
	man = engineLoadTXD("man.txd", 410)  
    engineImportTXD(man, 410)
	man = engineLoadDFF("man.dff", 410) 
	engineReplaceModel(man, 410)
	inf = engineLoadTXD("inf.txd", 411)  
    engineImportTXD(inf, 411)
	inf = engineLoadDFF("inf.dff", 411) 
	engineReplaceModel(inf, 411)
	bmwkombi = engineLoadTXD("bmwkombi.txd", 458)  
    engineImportTXD(bmwkombi, 458)
	bmwkombi = engineLoadDFF("bmwkombi.dff", 458) 
	engineReplaceModel(bmwkombi, 458)
	was = engineLoadTXD("was.txd", 421)  
    engineImportTXD(was, 421)
	was = engineLoadDFF("was.dff", 421) 
	engineReplaceModel(was, 421)
	cset = engineLoadTXD("cset.txd", 415)  
    engineImportTXD(cset, 415)
	cset = engineLoadDFF("cset.dff", 415) 
	engineReplaceModel(cset, 415)
	bob = engineLoadTXD("bob.txd", 422)  
    engineImportTXD(bob, 422)
	bob = engineLoadDFF("bob.dff", 422) 
	engineReplaceModel(bob, 422)
	prem = engineLoadTXD("prem.txd", 426)  
    engineImportTXD(prem, 426)
	prem = engineLoadDFF("prem.dff", 426) 
	engineReplaceModel(prem, 426)
	prev = engineLoadTXD("prev.txd", 436)  
    engineImportTXD(prev, 436)
	prev = engineLoadDFF("prev.dff", 436) 
	engineReplaceModel(prev, 436)
	ban = engineLoadTXD("ban.txd", 429)  
    engineImportTXD(ban, 429)
	ban = engineLoadDFF("ban.dff", 429) 
	engineReplaceModel(ban, 429)
	stal = engineLoadTXD("stal.txd", 439)  
    engineImportTXD(stal, 439)
	stal = engineLoadDFF("stal.dff", 439) 
	engineReplaceModel(stal, 439)
	lada = engineLoadTXD("lada.txd", 445)  
    engineImportTXD(lada, 445)
	lada = engineLoadDFF("lada.dff", 445) 
	engineReplaceModel(lada, 445)
	hummer = engineLoadTXD("hummer.txd", 470)  
    engineImportTXD(hummer, 470)
	hummer = engineLoadDFF("hummer.dff", 470) 
	engineReplaceModel(hummer, 470)
	sab = engineLoadTXD("sab.txd", 475)  
    engineImportTXD(sab, 475)
	sab = engineLoadDFF("sab.dff", 475) 
	engineReplaceModel(sab, 475)
	gren = engineLoadTXD("gren.txd", 492)  
    engineImportTXD(gren, 492)
	gren = engineLoadDFF("gren.dff", 492) 
	engineReplaceModel(gren, 492)
	maj = engineLoadTXD("maj.txd", 517)  
    engineImportTXD(maj, 517)
	maj = engineLoadDFF("maj.dff", 517) 
	engineReplaceModel(maj, 517)
	reg = engineLoadTXD("reg.txd", 479)  
    engineImportTXD(reg, 479)
	reg = engineLoadDFF("reg.dff", 479) 
	engineReplaceModel(reg, 479)
	com = engineLoadTXD("com.txd", 480)  
    engineImportTXD(com, 480)
	com = engineLoadDFF("com.dff", 480) 
	engineReplaceModel(com, 480)
	pon = engineLoadTXD("pon.txd", 413)  
    engineImportTXD(pon, 413)
	pon = engineLoadDFF("pon.dff", 413) 
	engineReplaceModel(pon, 413)
	kocsi = engineLoadTXD("kocsi.txd", 546)  
    engineImportTXD(kocsi, 546)
	kocsi = engineLoadDFF("kocsi.dff", 546) 
	engineReplaceModel(kocsi, 546)
	lex = engineLoadTXD("lex.txd", 560)  
    engineImportTXD(lex, 560)
	lex = engineLoadDFF("lex.dff", 560) 
	engineReplaceModel(lex, 560)
	club = engineLoadTXD("club.txd", 589)  
    engineImportTXD(club, 589)
	club = engineLoadDFF("club.dff", 589) 
	engineReplaceModel(club, 589)
	flas= engineLoadTXD("flas.txd", 565)  
    engineImportTXD(flas, 565)
	flas = engineLoadDFF("flas.dff", 565) 
	engineReplaceModel(flas, 565)
	ranc= engineLoadTXD("ranc.txd", 489)  
    engineImportTXD(ranc, 489)
	ranc = engineLoadDFF("ranc.dff", 489) 
	engineReplaceModel(ranc, 489)
	euros= engineLoadTXD("euros.txd", 587)  
    engineImportTXD(euros, 587)
	euros = engineLoadDFF("euros.dff", 587) 
	engineReplaceModel(euros, 587)
	bul= engineLoadTXD("bul.txd", 541)  
    engineImportTXD(bul, 541)
	bul= engineLoadDFF("bul.dff", 541) 
	engineReplaceModel(bul, 541)
	mesa= engineLoadTXD("mesa.txd", 500)  
    engineImportTXD(mesa, 500)
	mesa= engineLoadDFF("mesa.dff", 500) 
	engineReplaceModel(mesa, 500)
	dod= engineLoadTXD("dod.txd", 477)  
    engineImportTXD(dod, 477)
	dod= engineLoadDFF("dod.dff", 477) 
	engineReplaceModel(dod, 477)
	rumpo= engineLoadTXD("rumpo.txd", 482)  
    engineImportTXD(rumpo, 482)
	rumpo= engineLoadDFF("rumpo.dff", 482) 
	engineReplaceModel(rumpo, 482)

	
	
end
setTimer (StartVehMods, 1000, 1)

function StopVehMods()
 local model
 for model = 400,611,1 do
  engineRestoreModel (model)
 end
end


local kocsik = false
function kocsikresi()
    
        kocsik = not kocsik
        if kocsik == true then
            outputChatBox ("Kikapcsoltad a kocsik modólását",0, 250, 0, false)
			setTimer (StopVehMods, 1000, 1)
        else
            outputChatBox ("Bekapcsoltad a kocsik modólását", 250, 0, 0, false)
			setTimer (StartVehMods, 1000, 1)
        end
		end  
addCommandHandler("kocsik",kocsikresi, false)